### ISSUE TITLE
Version 9.0 "Workflow" - bereits gestarteten Workflow erneut öffnen (zB weil "Redaktion" den Workflow übernimmt) 

### ISSUE THREAD

**Issue by JSchindleruibk** [mic-men/es-test#22]
Getestet mit Version 9.0

**Wenn eine Resource eine Workflow History hat, kann das Fenster "Workflow" nicht mehr geöffnet werden.**

How to reproduce:

Resource im Workflow einem anderem User oder Gruppe zuweißen

Workflow der gleichen Resource öffnen

 

Es wird folgende Fehlermeldung geworfen: 

024-05-23T15:33:37,850 {ClientTraceId=10b2b59c-0983-4fa8-ad1e-b02b32cd0dfa} ERROR [restservices.shared.ErrorResponse] [http-nio-0.0.0.0-8081-exec-7] org.json.JSONException: JSONObject["time"] is not a string (class java.lang.Long : 1716478375344).
org.edu_sharing.restservices.DAOException: org.json.JSONException: JSONObject["time"] is not a string (class java.lang.Long : 1716478375344).
	at org.edu_sharing.restservices.DAOException.mapping(DAOException.java:135) ~[edu_sharing-community-repository-backend-services-core-maven-fixes-9.0-SNAPSHOT.jar:maven-fixes-9.0-SNAPSHOT]
	at org.edu_sharing.restservices.DAOException.mapping(DAOException.java:139) ~[edu_sharing-community-repository-backend-services-core-maven-fixes-9.0-SNAPSHOT.jar:maven-fixes-9.0-SNAPSHOT]
	at org.edu_sharing.restservices.NodeDao.getWorkflowHistory(NodeDao.java:2142) ~[edu_sharing-community-repository-backend-services-core-maven-fixes-9.0-SNAPSHOT.jar:maven-fixes-9.0-SNAPSHOT]
	at org.edu_sharing.restservices.node.v1.NodeApi.getWorkflowHistory(NodeApi.java:92) ~[edu_sharing-community-repository-backend-services-core-maven-fixes-9.0-SNAPSHOT.jar:maven-fixes-9.0-SNAPSHOT]

 

Das Problem ist in NodeDao.java in der Methode getWorkflowHistory() in der Anweisung history.setTime(Long.parseLong(json.getString("time"))); (Zeile 2135). Der Value von time ist kein String sondern ein Long. Ich vermute ein umändern auf history.setTime(json.getLong("time")); sollte das Problem lösen.

**Comment by JSchindleruibk** [comment]
bereits an metaventis gemeldet

**Comment by mic-men** [comment]
Fehler ist offenbar behoben. Getestet mit V9.0.18
